# Generated by Django 3.2 on 2023-11-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20231104_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Рейтинг'),
        ),
    ]
